Replace HIP_IFCS macro by simple if/else construct.
A macro to implement a simple if/else condition as a pseudofunction is a
very suspicious construct to begin with and in this case, it caused the
following compilation failure when optimizing for size (-Os):

modules/update/hipd/update.c: In function ‘hip_check_update_freshness’:
modules/update/hipd/update.c:152: error: inlining failed in call to ‘hip_update_get_out_id’: optimizing for size and code size would grow
modules/update/hipd/update.c:1040: error: called from here
modules/update/hipd/update.c:152: error: inlining failed in call to ‘hip_update_get_out_id’: optimizing for size and code size would grow
modules/update/hipd/update.c:1070: error: called from here
modules/update/hipd/update.c:152: error: inlining failed in call to ‘hip_update_get_out_id’: optimizing for size and code size would grow
modules/update/hipd/update.c:1072: error: called from here