Remove a non-crucial debug message that causes issues when compiling with -Os.
hipd/input.c: In function ‘hip_handle_r1’:
./lib/core/debug.h:418: error: inlining failed in call to ‘hip_state_str’: optimizing for size and code size would grow