Solved a problem with RPM packaged DNS proxy.
Bug id #715607 describes a problem with RPM packaged DNS proxy:

The DNS proxy is not using python APIs in way compatible with python 
2.7. Can we support both 2.6 and 2.7?

hipserver # /etc/init.d/hipdnsproxy start
Starting : [ OK ]
[root@hipserver hipl]# Traceback (most recent call last):
  File "/usr/sbin/hipdnsproxy", line 1029, in <module>
    main(sys.argv)
  File "/usr/sbin/hipdnsproxy", line 1026, in main
    gp.doit(args)
  File "/usr/sbin/hipdnsproxy", line 731, in doit
    gp.write_local_hits_to_hosts()
  File "/usr/sbin/hipdnsproxy", line 535, in write_local_hits_to_hosts
    if not gp.getaddr(hit):
  File "/usr/sbin/hipdnsproxy", line 410, in getaddr
    r = h.getaddr(ahn)
AttributeError: Hosts instance has no attribute 'getaddr'

The problem was that the system had also /usr/sbin/hosts.py which was 
located before the HIPL version of hosts.py in the module search path. I 
rolled the DNS proxy path to the front path and it started working 
again. Tested on Fedora Core 14 and Ubuntu Maverick.

If you have a more elegant solution, feel free to contribute.