Fixed bug 41 (telnet did not compile). Renamed libinet/include_glibc2*/Makefile.in files to Makefile.am and added them as subdirs in libinet6/Makefile.am. Ugly fix but works...
-------- Original Message --------
Subject:        HIP: libinet6 bug
Date:   Fri, 01 Apr 2005 13:43:59 +0200
From:   Per Toft <pnto03@kom.aau.dk>
To:     andrei.gurtov@cs.helsinki.fi, 05gr680@kom.auc.dk



Dear Andrei

We are a three engineer students working on an HIP evaluation project.

Unfortunately we have encountered a problem... Hope you can/will help
us.

We are currently using release 0.1.2. We have successfully installed the
HIP-enabled Kernel and the user-space tools. Also it has been possible
top perform a HIP-base exchange, however as we tried to install the
telnetd, telnet, tcpdump & etherreal, we encountered problems with
libinet6.

In the HIP-manual; It instructs us to configure libinet with
the ./configure command. However, the command does not exists.
see http://hipl.hiit.fi/hipl/manual/ch09.html

We can compile libinet6 with the make-command, but it causes trouble
when compiling telnet etc.

When compiling the telnet test program the output is as follows:

root@marge:/usr/src/hipl-0.1.2/test/telnet # make distclean
rm -f *.o telnet
rm -f config.*
rm Makefile
root@marge:/usr/src/hipl-0.1.2/test/telnet # ./configure
creating cache ./config.cache
checking for c++... c++
checking whether the C++ compiler (c++ -fpermissive  ) works... yes
checking whether the C++ compiler (c++ -fpermissive  ) is a
cross-compiler... no
checking whether we are using GNU C++... yes
checking whether c++ accepts -g... yes
checking how to run the C++ preprocessor... c++ -E
checking for a BSD compatible install... /usr/bin/install -c
checking how to run the C preprocessor... cc -E
checking for termcap.h... yes
checking for ncurses/termcap.h... no
checking for main in -lncurses... yes
updating cache ./config.cache
creating ./config.status
creating Makefile
root@marge:/usr/src/hipl-0.1.2/test/telnet # make
c++ -fpermissive  -I../../tools -I../../libinet6/include -I../..
-I../../linux/include -I../../linux/net/ipv6/hip -DUSE_HIP -g -D_USAGI
-DINET6  -DHAVE_TERMCAP_H=1 -DHAVE_LIBNCURSES=1  -DUSE_TERMIO
-DKLUDGELINEMODE   -c -o commands.o commands.cc
c++ -fpermissive  -I../../tools -I../../libinet6/include -I../..
-I../../linux/include -I../../linux/net/ipv6/hip -DUSE_HIP -g -D_USAGI
-DINET6  -DHAVE_TERMCAP_H=1 -DHAVE_LIBNCURSES=1  -DUSE_TERMIO
-DKLUDGELINEMODE   -c -o main.o main.ccc++ -fpermissive  -I../../tools
-I../../libinet6/include -I../.. -I../../linux/include
-I../../linux/net/ipv6/hip -DUSE_HIP -g -D_USAGI -DINET6
-DHAVE_TERMCAP_H=1 -DHAVE_LIBNCURSES=1  -DUSE_TERMIO -DKLUDGELINEMODE
-c -o network.o network.cc
c++ -fpermissive  -I../../tools -I../../libinet6/include -I../..
-I../../linux/include -I../../linux/net/ipv6/hip -DUSE_HIP -g -D_USAGI
-DINET6  -DHAVE_TERMCAP_H=1 -DHAVE_LIBNCURSES=1  -DUSE_TERMIO
-DKLUDGELINEMODE   -c -o ring.o ring.ccc++ -fpermissive  -I../../tools
-I../../libinet6/include -I../.. -I../../linux/include
-I../../linux/net/ipv6/hip -DUSE_HIP -g -D_USAGI -DINET6
-DHAVE_TERMCAP_H=1 -DHAVE_LIBNCURSES=1  -DUSE_TERMIO -DKLUDGELINEMODE
-c -o sys_bsd.o sys_bsd.cc
c++ -fpermissive  -I../../tools -I../../libinet6/include -I../..
-I../../linux/include -I../../linux/net/ipv6/hip -DUSE_HIP -g -D_USAGI
-DINET6  -DHAVE_TERMCAP_H=1 -DHAVE_LIBNCURSES=1  -DUSE_TERMIO
-DKLUDGELINEMODE   -c -o telnet.o telnet.cc
c++ -fpermissive  -I../../tools -I../../libinet6/include -I../..
-I../../linux/include -I../../linux/net/ipv6/hip -DUSE_HIP -g -D_USAGI
-DINET6  -DHAVE_TERMCAP_H=1 -DHAVE_LIBNCURSES=1  -DUSE_TERMIO
-DKLUDGELINEMODE   -c -o terminal.o terminal.cc
terminal.cc:473:9: warning: extra tokens at end of #endif directive
terminal.cc:509:9: warning: extra tokens at end of #endif directive
c++ -fpermissive  -I../../tools -I../../libinet6/include -I../..
-I../../linux/include -I../../linux/net/ipv6/hip -DUSE_HIP -g -D_USAGI
-DINET6  -DHAVE_TERMCAP_H=1 -DHAVE_LIBNCURSES=1  -DUSE_TERMIO
-DKLUDGELINEMODE   -c -o tn3270.o tn3270.cc
c++ -fpermissive  -I../../tools -I../../libinet6/include -I../..
-I../../linux/include -I../../linux/net/ipv6/hip -DUSE_HIP -g -D_USAGI
-DINET6  -DHAVE_TERMCAP_H=1 -DHAVE_LIBNCURSES=1  -DUSE_TERMIO
-DKLUDGELINEMODE   -c -o utilities.o utilities.cc
c++ -fpermissive  -I../../tools -I../../libinet6/include -I../..
-I../../linux/include -I../../linux/net/ipv6/hip -DUSE_HIP -g -D_USAGI
-DINET6  -DHAVE_TERMCAP_H=1 -DHAVE_LIBNCURSES=1  -DUSE_TERMIO
-DKLUDGELINEMODE   -c -o genget.o genget.cc
c++ -fpermissive  -I../../tools -I../../libinet6/include -I../..
-I../../linux/include -I../../linux/net/ipv6/hip -DUSE_HIP -g -D_USAGI
-DINET6  -DHAVE_TERMCAP_H=1 -DHAVE_LIBNCURSES=1  -DUSE_TERMIO
-DKLUDGELINEMODE   -c -o environ.o environ.cc
c++ -fpermissive  -I../../tools -I../../libinet6/include -I../..
-I../../linux/include -I../../linux/net/ipv6/hip -DUSE_HIP -g -D_USAGI
-DINET6  -DHAVE_TERMCAP_H=1 -DHAVE_LIBNCURSES=1  -DUSE_TERMIO
-DKLUDGELINEMODE   -c -o netlink.o netlink.cc
c++  commands.o main.o network.o ring.o sys_bsd.o telnet.o terminal.o
tn3270.o utilities.o genget.o environ.o netlink.o -L../../libinet6/.libs
-linet6 -lcrypto -lncurses  -o telnet
/usr/local/lib/libinet6.so: undefined reference to `SA_LEN'
collect2: ld returned 1 exit status
make: *** [telnet] Error 1
root@marge:/usr/src/hipl-0.1.2/test/telnet #

We have installed the libinet6 from HIP-0.1.2 into /usr/local/lib and
configured our ld-path.
We have also tried to use the folder ".libs" within libinet6-folder.
The outcome was the same.

The same problem: "/usr/local/lib/libinet6.so: undefined reference to
`SA_LEN'" occurs with all the test-programs. 
We have done some research on google and we think the problem is due to
the missing libinet6 configure script.

What to do?

 
Best regards
Lars, Gustav & Per

Aalborg University
Department of Communication technology
Denmark