Reorganized some code. The remaining errors need to be rewritten using regular XFRM messages:
beet.o: In function `hip_xfrm_update':
/home/mkomu/projects/hipl--beet--2.6/hipd/beet.c:379: undefined reference to `hip_netlink_talk'
beet.o: In function `hip_xfrm_delete':
/home/mkomu/projects/hipl--beet--2.6/hipd/beet.c:406: undefined reference to `hip_netlink_talk'
hipd.o: In function `main':
/home/mkomu/projects/hipl--beet--2.6/hipd/hipd.c:156: undefined reference to `hip_netlink_talk'
xfrm.o: In function `hip_delete_sa':
/home/mkomu/projects/hipl--beet--2.6/hipd/xfrm.c:21: undefined reference to `hip_netlink_talk'
xfrm.o: In function `hip_acquire_spi':
/home/mkomu/projects/hipl--beet--2.6/hipd/xfrm.c:55: undefined reference to `hip_netlink_talk'