De-inline hip_lp_next and move it from the .h file to the .c file.
The inlined function was causing trouble when compiling with -Os:
firewall/port_bindings.c: In function ‘hip_port_bindings_get’:
firewall/line_parser.h:97: error: inlining failed in call to ‘hip_lp_next’: optimizing for size and code size would grow
firewall/port_bindings.c:352: error: called from here
firewall/line_parser.h:97: error: inlining failed in call to ‘hip_lp_next’: optimizing for size and code size would grow
firewall/port_bindings.c:371: error: called from here

Since we need to build with -Os at least for OpenWrt, deinlining this
function appears to be the most sensible compromise.